species_insert:
    path: species/insert
    controller: App\Controller\SpeciesController::insert
    methods: [POST, HEAD, GET]

species_select:
    path: species/select
    controller: App\Controller\SpeciesController::select
    methods: [POST, HEAD, GET]

species_search:
    path: species/search
    controller: App\Controller\SpeciesController::search
    methods: [POST, HEAD, GET]

species_update:
    path: species/update
    controller: App\Controller\SpeciesController::update
    methods: [POST, HEAD, GET]

species_delete:
    path: species/delete
    controller: App\Controller\SpeciesController::delete
    methods: [POST, HEAD, GET]



popularName_insert:
    path: popularName/insert
    controller: App\Controller\PopularNameController::insert
    methods: [POST, HEAD, GET]

popularName_select:
    path: popularName/select
    controller: App\Controller\PopularNameController::select
    methods: [POST, HEAD, GET]

popularName_update:
    path: popularName/update
    controller: App\Controller\PopularNameController::update
    methods: [POST, HEAD, GET]


user_insert:
    path: user/insert
    controller: App\Controller\UserController::insert
    methods: [POST, HEAD, GET]

user_validate:
    path: user/validate
    controller: App\Controller\UserController::validate
    methods: [HEAD, GET, POST]



