species_insert:
    path: species/insert
    controller: App\Controller\SpeciesController::insert
    methods: [POST, HEAD, GET]

species_select:
    path: species/select
    controller: App\Controller\SpeciesController::select
    methods: [POST, HEAD, GET]

species_select_all:
    path: species/selectAll
    controller: App\Controller\SpeciesController::selectAll
    methods: [POST, HEAD, GET]

species_search:
    path: species/search
    controller: App\Controller\SpeciesController::search
    methods: [POST, HEAD, GET]

species_update:
    path: species/update
    controller: App\Controller\SpeciesController::update
    methods: [POST, HEAD, GET]



popularName_insert:
    path: popularName/insert
    controller: App\Controller\PopularNameController::insert
    methods: [POST, HEAD, GET]

popularName_selectAll:
    path: popularName/selectAll
    controller: App\Controller\PopularNameController::selectAll
    methods: [POST, HEAD, GET]

popularName_selectAllFromSpecies:
    path: popularName/selectAllFromSpecies
    controller: App\Controller\PopularNameController::selectAllFromSpecies
    methods: [POST, HEAD, GET]

popularName_select:
    path: popularName/select
    controller: App\Controller\PopularNameController::select
    methods: [POST, HEAD, GET]

popularName_update:
    path: popularName/update
    controller: App\Controller\PopularNameController::update
    methods: [POST, HEAD, GET]

popularName_delete:
    path: popularName/delete
    controller: App\Controller\PopularNameController::delete
    methods: [POST, HEAD, GET]


user_insert:
    path: user/insert
    controller: App\Controller\UserController::insert
    methods: [POST, HEAD, GET]

user_validate:
    path: user/validate
    controller: App\Controller\UserController::validate
    methods: [HEAD, GET, POST]

user_update_status:
    path: user/updateStatus
    controller: App\Controller\UserController::updateStatus
    methods: [HEAD, GET, POST]

user_recover_password:
    path: user/recoverPassword
    controller: App\Controller\UserController::recoverPassword
    methods: [HEAD, GET, POST]



